# Generated by Django 5.2.17 on 2026-09-09 06:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='directory_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='photo_key',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='share_bio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='share_contacts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='share_experiences',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='share_mandates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='share_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='share_profession',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AssociationExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('network', models.CharField(choices=[('LIONS', 'Lions'), ('LEO', 'LEO')], max_length=5)),
                ('club', models.CharField(max_length=150)),
                ('function', models.CharField(max_length=150)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('starts_on', models.DateField(help_text='Mois de début, enregistré au premier jour')),
                ('ends_on', models.DateField(blank=True, help_text='Mois de fin inclus', null=True)),
                ('description', models.TextField(blank=True, max_length=1500)),
                ('achievements', models.TextField(blank=True, max_length=1500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiences', to='members.memberprofile')),
            ],
            options={
                'ordering': ['-starts_on', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('network__in', ['LIONS', 'LEO'])), name='experience_network_valid'), models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='experience_dates_ordered'), models.CheckConstraint(condition=models.Q(('starts_on__day', 1), models.Q(('ends_on__isnull', True), ('ends_on__day', 1), _connector='OR')), name='experience_month_precision')],
            },
        ),
    ]
