# Generated by Django 5.2.17 on 2026-09-09 07:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_memberprofile_bio_memberprofile_directory_visible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_key', models.UUIDField(unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('motivation', models.TextField(max_length=5000)),
                ('origin', models.CharField(blank=True, max_length=40)),
                ('state', models.CharField(choices=[('RECEIVED', 'Reçue'), ('CONTACTED', 'Contact établi'), ('FOLLOW_UP', 'En suivi'), ('CLOSED', 'Close')], default='RECEIVED', max_length=12)),
                ('notice_version', models.CharField(default='lot3-v1', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ['RECEIVED', 'CONTACTED', 'FOLLOW_UP', 'CLOSED'])), name='application_state_valid')],
            },
        ),
    ]
