# Generated by Django 5.2.17 on 2026-09-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_membershipapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipapplication',
            name='phone',
            field=models.CharField(help_text='Obligatoire pour vous recontacter au sujet de votre candidature.', max_length=32),
        ),
    ]
