# Generated by Django 5.2.17 on 2026-09-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_public_profile_and_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='is_vote_manager',
            field=models.BooleanField(default=False),
        ),
    ]
