# Generated by Django 5.2.17 on 2026-09-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_memberprofile_is_vote_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='calendar_token',
            field=models.CharField(blank=True, editable=False, max_length=43, null=True, unique=True),
        ),
    ]
