# Generated by Django 5.2.17 on 2026-09-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_memberprofile_calendar_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='public_title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
