# Generated by Django 5.2.17 on 2026-09-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_memberprofile_public_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='photo_crop',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='photo_original_key',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
