# Generated by Django 5.2.17 on 2026-09-09 07:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_publicimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(max_length=300, unique=True)),
                ('new_path', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubIdentity',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('postal_address', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(max_length=300)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='identity_singleton')],
            },
        ),
        migrations.CreateModel(
            name='EditorialSection',
            fields=[
                ('key', models.CharField(choices=[('club_intro', 'Présentation du club'), ('club_history', 'Histoire documentée'), ('club_values', 'Valeurs'), ('club_movement', 'Mouvement Lions'), ('join_service', 'Rejoindre : servir'), ('join_belonging', 'Rejoindre : appartenir'), ('join_growth', 'Rejoindre : progresser'), ('legal', 'Mentions légales'), ('privacy', 'Confidentialité'), ('axis_diabete', 'Axe Diabète'), ('axis_environnement', 'Axe Environnement'), ('axis_humanitaire', 'Axe Humanitaire'), ('axis_jeunesse', 'Axe Jeunesse')], max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField(max_length=20000)),
                ('source', models.CharField(max_length=300)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('key__in', ['club_intro', 'club_history', 'club_values', 'club_movement', 'join_service', 'join_belonging', 'join_growth', 'legal', 'privacy', 'axis_diabete', 'axis_environnement', 'axis_humanitaire', 'axis_jeunesse'])), name='editorial_known_key')],
            },
        ),
        migrations.CreateModel(
            name='ImpactMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField()),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('source', models.CharField(max_length=300)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='metric_dates')],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.TextField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True, max_length=20000)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('REVIEW', 'À valider'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Retiré')], default='DRAFT', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(choices=[('VIE', 'Vie du club'), ('PASSATION', 'Passation'), ('PARTENARIAT', 'Partenariat'), ('DISTINCTION', 'Distinction'), ('COMMUNIQUE', 'Communiqué')], default='VIE', max_length=20)),
                ('author_name', models.CharField(blank=True, help_text='Signature publique validée seulement', max_length=150)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_covers', to='core.publicimage')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_socials', to='core.publicimage')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', 'id'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED'])), name='editorial_newsarticle_status'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'PUBLISHED'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='editorial_newsarticle_pub_date')],
            },
        ),
    ]
