# Generated by Django 5.2.17 on 2026-09-09 08:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_publicimage'),
        ('governance', '0002_mandate'),
        ('members', '0003_membershipapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vote_electorships', to='members.memberprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('elector', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='participation', to='voting.elector')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('OPEN', 'Ouvert'), ('CLOSED', 'Clôturé')], default='DRAFT', max_length=8)),
                ('mode', models.CharField(choices=[('SINGLE', 'Choix unique'), ('MULTIPLE', 'Choix multiple'), ('ELECTION', 'Élection')], default='SINGLE', max_length=10)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('min_choices', models.PositiveSmallIntegerField(default=1)),
                ('max_choices', models.PositiveSmallIntegerField(default=1)),
                ('blank_allowed', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, help_text="Horodatage réel d'ouverture ; fige les électeurs", null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votes_closed', to=settings.AUTH_USER_MODEL)),
                ('lions_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='governance.lionsyear')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes_managed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_voting_vote',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='elector',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electors', to='voting.vote'),
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_blank', models.BooleanField(default=False)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='voting.vote')),
            ],
        ),
        migrations.CreateModel(
            name='VoteOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=180)),
                ('presentation', models.TextField(blank=True, max_length=2000)),
                ('order', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidacies', to='members.memberprofile')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vote_option_photos', to='core.publicimage')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='voting.vote')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BallotSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='voting.ballot')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='voting.voteoption')),
            ],
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(condition=models.Q(('closes_at__gt', models.F('opens_at'))), name='vote_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(condition=models.Q(('min_choices__gte', 1), ('max_choices__gte', models.F('min_choices'))), name='vote_cardinality_valid'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'OPEN', 'CLOSED'])), name='vote_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ['SINGLE', 'MULTIPLE', 'ELECTION'])), name='vote_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='elector',
            constraint=models.UniqueConstraint(fields=('vote', 'profile'), name='elector_unique_vote_profile'),
        ),
        migrations.AddConstraint(
            model_name='voteoption',
            constraint=models.UniqueConstraint(fields=('vote', 'order'), name='voteoption_unique_order'),
        ),
        migrations.AddConstraint(
            model_name='ballotselection',
            constraint=models.UniqueConstraint(fields=('ballot', 'option'), name='ballotselection_unique_ballot_option'),
        ),
    ]
