# Generated by Django 5.2.17 on 2026-09-09 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_mandate'),
        ('voting', '0002_ballotselection_vote_match_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='vote_dates_ordered',
        ),
        migrations.AlterField(
            model_name='vote',
            name='closes_at',
            field=models.DateTimeField(blank=True, help_text='Vide : le scrutin ne se ferme que manuellement.', null=True),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(condition=models.Q(('closes_at__isnull', True), ('closes_at__gt', models.F('opens_at')), _connector='OR'), name='vote_dates_ordered'),
        ),
    ]
