# Generated by Django 5.2.17 on 2026-09-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_remove_vote_vote_dates_ordered_alter_vote_closes_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='creation_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
