# Generated by Django 5.2.17 on 2026-09-25 13:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0005_remove_rolegrant_grant_role_valid_and_more'),
        ('voting', '0004_vote_creation_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NominativeChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_blank', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='disclosure',
            field=models.CharField(choices=[('SECRET', 'Vote secret'), ('NOMINATIVE', 'Vote nominatif')], default='SECRET', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(condition=models.Q(('disclosure__in', ['SECRET', 'NOMINATIVE'])), name='vote_disclosure_valid'),
        ),
        migrations.AddField(
            model_name='nominativechoice',
            name='elector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='nominative_choice', to='voting.elector'),
        ),
        migrations.AddField(
            model_name='nominativechoice',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='nominative_choices', to='voting.voteoption'),
        ),
    ]
