# Generated by Django 5.2.17 on 2026-09-09 08:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_membershipapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='Premier jour du mois concerné', unique=True)),
                ('rule_version', models.CharField(max_length=32)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('threshold', models.PositiveSmallIntegerField(default=5, help_text='Effectif minimal avant affichage des résultats — valeur de test, production À CONFIRMER HUMAINEMENT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='satisfaction_periods_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='SatisfactionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='satisfaction.satisfactionperiod')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='satisfaction_responses', to='members.memberprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='satisfactionperiod',
            constraint=models.CheckConstraint(condition=models.Q(('month__day', 1)), name='satisfaction_period_month_first_day'),
        ),
        migrations.AddConstraint(
            model_name='satisfactionperiod',
            constraint=models.CheckConstraint(condition=models.Q(('opens_at__isnull', True), ('closes_at__isnull', True), ('closes_at__gt', models.F('opens_at')), _connector='OR'), name='satisfaction_period_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='satisfactionperiod',
            constraint=models.CheckConstraint(condition=models.Q(('threshold__gte', 1)), name='satisfaction_period_threshold_positive'),
        ),
        migrations.AddConstraint(
            model_name='satisfactionresponse',
            constraint=models.UniqueConstraint(fields=('period', 'profile'), name='satisfaction_unique_period_profile'),
        ),
        migrations.AddConstraint(
            model_name='satisfactionresponse',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='satisfaction_score_range'),
        ),
    ]
