# Generated by Django 5.2.17 on 2026-09-15 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfactionperiod',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='satisfactionperiod',
            name='title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.CreateModel(
            name='SatisfactionAxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=180)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axes', to='satisfaction.satisfactionperiod')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SatisfactionAxisScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='satisfaction.satisfactionaxis')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='axis_scores', to='satisfaction.satisfactionresponse')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('response', 'axis'), name='satisfaction_unique_axis_score'), models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='satisfaction_axis_score_range')],
            },
        ),
    ]
