# Generated by Django 5.2.17 on 2026-09-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction', '0002_satisfactionperiod_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfactionperiod',
            name='month',
            field=models.DateField(help_text='Premier jour du mois concerné'),
        ),
    ]
