# Generated by Django 5.2.1 on 2026-08-20 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Année')),
                ('members_count', models.IntegerField(default=0, verbose_name='Nombre de membres')),
                ('projects_count', models.IntegerField(default=0, verbose_name='Nombre de projets')),
                ('beneficiaries_count', models.IntegerField(default=0, verbose_name='Nombre de bénéficiaires')),
                ('years_of_existence', models.IntegerField(default=1, help_text='Depuis la fondation du club en 2025', verbose_name="Années d'existence")),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Statistique du Club',
                'verbose_name_plural': 'Statistiques du Club',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='ClubValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre de la valeur')),
                ('description', models.TextField(verbose_name='Description de la valeur')),
                ('icon_svg_name', models.CharField(help_text="Ex: 'heart', 'shield', 'users', etc.", max_length=50, verbose_name="Nom de l'icône SVG")),
                ('tagline', models.CharField(help_text="Ex: 'We Serve', 'Éthique absolue'", max_length=200, verbose_name='Slogan/Tagline')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Valeur du Club',
                'verbose_name_plural': 'Valeurs du Club',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DomainAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre du domaine')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('icon', models.CharField(choices=[('eye', 'Œil — Vision'), ('heart', 'Cœur — Santé'), ('graduation-cap', 'Mortier — Éducation'), ('leaf', 'Feuille — Environnement'), ('moon', 'Lune — Lutte contre la faim'), ('zap', "Éclair — Aide d'urgence")], max_length=20, verbose_name='Icône')),
                ('color', models.CharField(choices=[('blue', 'Bleu'), ('red', 'Rouge'), ('amber', 'Ambre'), ('green', 'Vert'), ('orange', 'Orange'), ('purple', 'Violet')], max_length=20, verbose_name='Couleur')),
                ('stat_label', models.CharField(help_text="Ex: 'Actions à venir', 'Prévention de proximité'", max_length=100, verbose_name='Label de statut')),
                ('order', models.IntegerField(default=0, help_text='Les domaines sont triés par ce champ', verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': "Domaine d'Action",
                'verbose_name_plural': "Domaines d'Action",
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du jalon')),
                ('description', models.TextField(verbose_name='Description du jalon')),
                ('is_active_milestone', models.BooleanField(default=False, help_text='Mettre en évidence ce jalon comme important', verbose_name='Jalon actif')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Jalon Historique',
                'verbose_name_plural': 'Jalons Historiques',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='MembershipBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name="Titre de l'avantage")),
                ('description', models.TextField(verbose_name="Description de l'avantage")),
                ('icon_name', models.CharField(help_text="Ex: 'users', 'zap', 'book', 'star'", max_length=50, verbose_name="Nom de l'icône")),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': "Avantage de l'Adhésion",
                'verbose_name_plural': "Avantages de l'Adhésion",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Lions Club Sfax Méditerranée', max_length=100, verbose_name='Nom du club')),
                ('founded_year', models.IntegerField(default=2025, verbose_name='Année de fondation')),
                ('email_contact', models.EmailField(default='secretariat@lionsmed.tn', max_length=254, verbose_name='Email de contact')),
                ('phone_contact', models.CharField(default='+216 00 000 000', max_length=20, verbose_name='Téléphone de contact')),
                ('address', models.CharField(default='Sfax — Tunisie', max_length=200, verbose_name='Adresse du club')),
                ('monthly_meeting_day', models.CharField(default='2e lundi de chaque mois', help_text='Ex: 2e lundi de chaque mois', max_length=100, verbose_name='Jour des réunions mensuelles')),
                ('monthly_meeting_time', models.TimeField(default='19:00', verbose_name='Heure des réunions mensuelles')),
                ('mission_text', models.TextField(blank=True, default='', verbose_name='Texte de la mission')),
                ('vision_text', models.TextField(blank=True, default='', verbose_name='Texte de la vision')),
                ('history_intro', models.TextField(blank=True, default='', verbose_name='Introduction historique')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Configuration du Site',
                'verbose_name_plural': 'Configuration du Site',
            },
        ),
        migrations.CreateModel(
            name='BureauMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Description professionnelle et personnelle', verbose_name='Biographie détaillée')),
                ('role_description', models.CharField(blank=True, help_text="Ex: 'Coordinatrice du programme Vision'", max_length=200, verbose_name='Fonction au sein du bureau')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='URL LinkedIn')),
                ('email_bureau', models.EmailField(blank=True, help_text='Email personnel du membre (optionnel)', max_length=254, verbose_name='Email du bureau')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible sur le site')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.OneToOneField(help_text='Sélectionnez un utilisateur avec rôle BUREAU, PRESIDENT, etc.', on_delete=django.db.models.deletion.CASCADE, related_name='bureau_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur du club')),
            ],
            options={
                'verbose_name': 'Membre du Bureau',
                'verbose_name_plural': 'Membres du Bureau',
                'ordering': ['order'],
            },
        ),
    ]
