# Generated by Django 5.2.17 on 2026-09-09 07:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_publicimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.TextField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True, max_length=20000)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('REVIEW', 'À valider'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Retiré')], default='DRAFT', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('axis', models.CharField(choices=[('DIABETE', 'Diabète'), ('ENVIRONNEMENT', 'Environnement'), ('HUMANITAIRE', 'Humanitaire'), ('JEUNESSE', 'Jeunesse')], max_length=20)),
                ('performed_on', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('beneficiaries', models.PositiveIntegerField(blank=True, null=True)),
                ('partners', models.TextField(blank=True, max_length=1000)),
                ('evidence', models.CharField(blank=True, help_text='Source du bilan, bénéficiaires ou partenaires', max_length=300)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_covers', to='core.publicimage')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_socials', to='core.publicimage')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='service_actions.action')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.publicimage')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED'])), name='service_actions_action_status'),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PUBLISHED'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='service_actions_action_pub_date'),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.CheckConstraint(condition=models.Q(('axis__in', ['DIABETE', 'ENVIRONNEMENT', 'HUMANITAIRE', 'JEUNESSE'])), name='action_axis_valid'),
        ),
        migrations.AddConstraint(
            model_name='actionphoto',
            constraint=models.UniqueConstraint(fields=('action', 'position'), name='action_photo_position'),
        ),
        migrations.AddConstraint(
            model_name='actionphoto',
            constraint=models.UniqueConstraint(fields=('action', 'image'), name='action_photo_image'),
        ),
    ]
