# Generated by Django 5.2.1 on 2026-08-20 11:49

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message="Format d'image non accepté. Extensions autorisées : %(allowed_extensions)s."), core.validators.MaxFileSizeValidator(5242880), core.validators.ImageContentValidator()]),
        ),
    ]
