# Generated by Django 5.2.17 on 2026-09-09 02:24

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGistExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='LionsYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateField(unique=True)),
                ('ends_on', models.DateField(help_text='Borne de fin exclusive')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-starts_on'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_on__gt', models.F('starts_on'))), name='year_dates_ordered'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(models.Func('starts_on', 'ends_on', models.Value('[)'), function='DATERANGE', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&')], name='year_no_overlap')],
            },
        ),
        migrations.CreateModel(
            name='ClubState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('active_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='governance.lionsyear')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='club_state_singleton')],
            },
        ),
        migrations.CreateModel(
            name='RoleGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super administrateur'), ('DIRECTEUR', 'Directeur'), ('PRESIDENT', 'Président'), ('SECRETAIRE', 'Secrétaire'), ('BUREAU', 'Bureau'), ('MEMBRE', 'Membre'), ('INVITE', 'Invité')], max_length=16)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_grants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'starts_at'], name='grant_user_start_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('role__in', ['SUPER_ADMIN', 'DIRECTEUR', 'PRESIDENT', 'SECRETAIRE', 'BUREAU', 'MEMBRE', 'INVITE'])), name='grant_role_valid'), models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='grant_dates_ordered'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('revoked_at__isnull', True)), expressions=[('user', '='), (models.Func('starts_at', 'ends_at', models.Value('[)'), function='TSTZRANGE', output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField()), '&&')], name='grant_no_overlap')],
            },
        ),
    ]
