# Generated by Django 5.2.17 on 2026-09-09 06:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
        ('members', '0002_memberprofile_bio_memberprofile_directory_visible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('function', models.CharField(max_length=150)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(help_text='Borne de fin exclusive')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('public_authorized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lions_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandates', to='governance.lionsyear')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandates', to='members.memberprofile')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_on', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_on__gt', models.F('starts_on'))), name='mandate_dates_ordered'), models.CheckConstraint(condition=models.Q(models.Q(('validated_at__isnull', True), ('validated_by__isnull', True)), models.Q(('validated_at__isnull', False), ('validated_by__isnull', False)), _connector='OR'), name='mandate_validation_pair')],
            },
        ),
    ]
