# Generated by Django 5.2.17 on 2026-09-09 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_mandate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rolegrant',
            name='grant_role_valid',
        ),
        migrations.AlterField(
            model_name='rolegrant',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super administrateur'), ('DIRECTEUR', 'Directeur'), ('PRESIDENT', 'Président'), ('VICE_PRESIDENT', 'Vice-président'), ('SECRETAIRE', 'Secrétaire'), ('TRESORIER', 'Trésorier'), ('BUREAU', 'Bureau'), ('GST', 'GST'), ('GMT', 'GMT'), ('GLT', 'GLT'), ('LCIF', 'LCIF'), ('MEMBRE', 'Membre'), ('INVITE', 'Invité')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='rolegrant',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['SUPER_ADMIN', 'DIRECTEUR', 'PRESIDENT', 'VICE_PRESIDENT', 'SECRETAIRE', 'TRESORIER', 'BUREAU', 'GST', 'GMT', 'GLT', 'LCIF', 'MEMBRE', 'INVITE'])), name='grant_role_valid'),
        ),
    ]
