# Generated by Django 5.2.17 on 2026-09-09 07:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('governance', '0002_mandate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('category', models.CharField(choices=[('GENERAL', 'Général'), ('GOUVERNANCE', 'Gouvernance'), ('FINANCIER', 'Financier'), ('DISTRICT', 'District'), ('AUTRE', 'Autre')], default='GENERAL', max_length=15)),
                ('visibility', models.CharField(choices=[('MEMBERS', 'Membres'), ('BUREAU', 'Bureau'), ('RESPONSABLES', 'Responsables')], default='MEMBERS', max_length=15)),
                ('status', models.CharField(choices=[('QUARANTINE', 'En quarantaine'), ('AVAILABLE', 'Disponible'), ('REJECTED', 'Rejeté')], default='QUARANTINE', max_length=10)),
                ('storage_key', models.CharField(editable=False, max_length=120)),
                ('original_filename', models.CharField(editable=False, max_length=255)),
                ('content_type', models.CharField(editable=False, max_length=100)),
                ('size', models.PositiveIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_authored', to=settings.AUTH_USER_MODEL)),
                ('lions_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='governance.lionsyear')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='documents.document')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_grants_issued', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['GENERAL', 'GOUVERNANCE', 'FINANCIER', 'DISTRICT', 'AUTRE'])), name='document_category_valid'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['MEMBERS', 'BUREAU', 'RESPONSABLES'])), name='document_visibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['QUARANTINE', 'AVAILABLE', 'REJECTED'])), name='document_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='documentgrant',
            constraint=models.UniqueConstraint(fields=('document', 'user'), name='document_grant_unique_document_user'),
        ),
    ]
