# Generated by Django 5.2.17 on 2026-09-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_publicimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('table', models.CharField(max_length=100)),
                ('legacy_pk', models.CharField(max_length=64)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('batch', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('IMPORTED', 'Importé'), ('REJECTED', 'Rejeté'), ('QUARANTINE', 'Quarantaine')], max_length=12)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'state'], name='legacy_import_batch_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'table', 'legacy_pk'), name='legacy_import_unique_source_table_pk')],
            },
        ),
    ]
