# Generated by Django 5.2.17 on 2026-10-06 17:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxState',
            fields=[
                ('mailbox', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('uid_validity', models.PositiveBigIntegerField(blank=True, null=True)),
                ('last_uid', models.PositiveBigIntegerField(default=0)),
                ('silent_until_uid', models.PositiveBigIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('failures', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=24)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mailbox', models.CharField(max_length=40)),
                ('uid_validity', models.PositiveBigIntegerField()),
                ('uid', models.PositiveBigIntegerField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('references', models.TextField(blank=True)),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('sender_address', models.CharField(blank=True, max_length=254)),
                ('reply_to', models.CharField(blank=True, max_length=254)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('copies', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField()),
                ('preview', models.CharField(blank=True, max_length=200)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('size', models.PositiveIntegerField(default=0)),
                ('partial', models.BooleanField(default=False)),
                ('automatic', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at', '-uid'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mailbox', models.CharField(max_length=40)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('recipients', models.JSONField(default=list)),
                ('copies', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(max_length=180)),
                ('body', models.TextField(max_length=20000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mailbox_messages', to=settings.AUTH_USER_MODEL)),
                ('in_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='mailboxes.inboundemail')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='inboundemail',
            index=models.Index(fields=['mailbox', '-received_at'], name='inbound_email_mailbox_idx'),
        ),
        migrations.AddConstraint(
            model_name='inboundemail',
            constraint=models.UniqueConstraint(fields=('mailbox', 'uid_validity', 'uid'), name='inbound_email_uid_unique'),
        ),
        migrations.AddConstraint(
            model_name='inboundemail',
            constraint=models.UniqueConstraint(fields=('mailbox', 'fingerprint'), name='inbound_email_fingerprint_unique'),
        ),
        migrations.AddIndex(
            model_name='outgoingemail',
            index=models.Index(fields=['mailbox', '-created_at'], name='outgoing_email_mailbox_idx'),
        ),
    ]
