# Generated by Django 5.2.17 on 2026-09-09 07:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_key', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('GENERAL', 'Question générale'), ('PARTENARIAT', 'Proposition de partenariat'), ('ACTION', 'Action ou initiative'), ('PRESSE', 'Presse / communication'), ('ADHESION', 'Question sur l’adhésion'), ('AUTRE', 'Autre demande')], max_length=20)),
                ('message', models.TextField(max_length=5000)),
                ('state', models.CharField(choices=[('RECEIVED', 'Reçu'), ('CONTACTED', 'Contact établi'), ('FOLLOW_UP', 'En suivi'), ('CLOSED', 'Clos')], default='RECEIVED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice_version', models.CharField(default='lot3-v1', max_length=32)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ['RECEIVED', 'CONTACTED', 'FOLLOW_UP', 'CLOSED'])), name='contact_state_valid')],
            },
        ),
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_key', models.CharField(max_length=150, unique=True)),
                ('kind', models.CharField(choices=[('APPLICATION', 'Accusé candidature'), ('CONTACT', 'Avis contact interne')], max_length=20)),
                ('recipient', models.EmailField(max_length=254)),
                ('object_id', models.UUIDField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('state', models.CharField(choices=[('PENDING', 'En attente'), ('SENDING', 'En cours'), ('SENT', 'Envoyé'), ('FAILED', 'Échec')], default='PENDING', max_length=8)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'available_at'], name='outbox_ready_idx')],
            },
        ),
    ]
