# Generated by Django 5.2.17 on 2026-09-09 07:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxmessage',
            name='kind',
            field=models.CharField(choices=[('APPLICATION', 'Accusé candidature'), ('CONTACT', 'Avis contact interne'), ('EVENT_REMINDER', 'Rappel de rendez-vous'), ('IMPORTANT', 'Notification importante'), ('DOCUMENT', 'Nouveau document')], max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_key', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('EVENT', 'Rendez-vous'), ('DOCUMENT', 'Document'), ('DUES', 'Cotisation'), ('IMPORTANT', 'Importante')], max_length=12)),
                ('title', models.CharField(max_length=180)),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('target_kind', models.CharField(blank=True, max_length=20)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', 'created_at'], name='notification_recipient_idx')],
            },
        ),
    ]
