# Generated by Django 5.2.17 on 2026-09-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_outboxmessage_kind_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('EVENT', 'Rendez-vous'), ('DOCUMENT', 'Document'), ('DUES', 'Cotisation'), ('IMPORTANT', 'Importante'), ('VOTE', 'Vote'), ('SATISFACTION', 'Satisfaction')], max_length=12),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='kind',
            field=models.CharField(choices=[('APPLICATION', 'Accusé candidature'), ('CONTACT', 'Avis contact interne'), ('EVENT_REMINDER', 'Rappel de rendez-vous'), ('IMPORTANT', 'Notification importante'), ('DOCUMENT', 'Nouveau document'), ('VOTE_OPENED', "Ouverture d'un vote"), ('VOTE_RESULTS', "Résultats d'un vote"), ('SATISFACTION_OPENED', 'Ouverture satisfaction')], max_length=20),
        ),
    ]
