# Generated by Django 5.2.17 on 2026-09-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_alter_outboxmessage_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxmessage',
            name='kind',
            field=models.CharField(choices=[('APPLICATION', 'Accusé candidature'), ('CONTACT', 'Avis contact interne'), ('EVENT_CREATED', 'Nouvel événement'), ('EVENT_REMINDER', 'Rappel de rendez-vous'), ('IMPORTANT', 'Notification importante'), ('DOCUMENT', 'Nouveau document'), ('VOTE_OPENED', "Ouverture d'un vote"), ('VOTE_RESULTS', "Résultats d'un vote"), ('SATISFACTION_OPENED', 'Ouverture satisfaction'), ('MEMBER_BROADCAST', 'Communication aux membres'), ('ACTIVATION', 'Invitation membre')], max_length=20),
        ),
    ]
