# Generated by Django 5.2.17 on 2026-09-15 21:13

from django.db import migrations, models


def backfill_internal_recipient_count(apps, schema_editor):
    # Champs nouveaux : toute campagne existante a été envoyée avant l'introduction du
    # ciblage — donc forcément à ALL_ACTIVE (déjà le défaut) et sans adresse externe
    # (déjà [] par défaut). Seul internal_recipient_count doit être recopié depuis
    # recipient_count, qui représentait jusqu'ici uniquement des membres internes.
    MemberEmailCampaign = apps.get_model("communications", "MemberEmailCampaign")
    MemberEmailCampaign.objects.update(internal_recipient_count=models.F("recipient_count"))


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_alter_outboxmessage_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberemailcampaign',
            name='audience',
            field=models.CharField(choices=[('ALL_ACTIVE', 'Tous les membres actifs'), ('RESPONSIBLES', 'Responsables uniquement')], default='ALL_ACTIVE', max_length=12),
        ),
        migrations.AddField(
            model_name='memberemailcampaign',
            name='external_emails',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='memberemailcampaign',
            name='internal_recipient_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_internal_recipient_count, migrations.RunPython.noop),
    ]
