# Generated by Django 5.2.17 on 2026-10-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0008_memberemailcampaign_audience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberemailcampaign',
            name='audience',
            field=models.CharField(choices=[('ALL_ACTIVE', 'Tous les membres actifs'), ('RESPONSIBLES', 'Responsables uniquement'), ('SELECTION', 'Sélection de membres')], default='ALL_ACTIVE', max_length=12),
        ),
    ]
