# Generated by Django 5.2.17 on 2026-10-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_alter_memberemailcampaign_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberemailcampaign',
            name='sender_mailbox',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='outboxmessage',
            name='sender_mailbox',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('EVENT', 'Rendez-vous'), ('DOCUMENT', 'Document'), ('DUES', 'Cotisation'), ('IMPORTANT', 'Importante'), ('VOTE', 'Vote'), ('SATISFACTION', 'Satisfaction'), ('MESSAGE', 'Messagerie')], max_length=12),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='kind',
            field=models.CharField(choices=[('APPLICATION', 'Accusé candidature'), ('CONTACT', 'Avis contact interne'), ('EVENT_CREATED', 'Nouvel événement'), ('EVENT_REMINDER', 'Rappel de rendez-vous'), ('IMPORTANT', 'Notification importante'), ('DOCUMENT', 'Nouveau document'), ('VOTE_OPENED', "Ouverture d'un vote"), ('VOTE_RESULTS', "Résultats d'un vote"), ('SATISFACTION_OPENED', 'Ouverture satisfaction'), ('MEMBER_BROADCAST', 'Communication aux membres'), ('ACTIVATION', 'Invitation membre'), ('MAILBOX_MESSAGE', "Message d'une boîte institutionnelle"), ('MAILBOX_NOTICE', 'Avis de nouveau message')], max_length=20),
        ),
    ]
