# Generated by Django 5.2.17 on 2026-09-09 07:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_publicimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.TextField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True, max_length=20000)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('REVIEW', 'À valider'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Retiré')], default='DRAFT', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('RENCONTRE', 'Rencontre'), ('REUNION', 'Réunion'), ('FORMATION', 'Formation'), ('AUTRE', 'Autre')], default='RENCONTRE', max_length=20)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Privé')], default='PRIVATE', max_length=8)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_covers', to='core.publicimage')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_socials', to='core.publicimage')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', 'id'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED'])), name='agenda_event_status'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'PUBLISHED'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='agenda_event_pub_date'), models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), models.Q(('ends_at__gt', models.F('starts_at')), ('starts_at__isnull', False)), _connector='OR'), name='event_dates_valid')],
            },
        ),
    ]
