# Generated by Django 5.2.17 on 2026-09-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_attendance_registration_event_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='all_day',
            field=models.BooleanField(default=False, help_text="Événement journée entière — heures ignorées à l'affichage."),
        ),
        migrations.AddField(
            model_name='event',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Lien de réunion (visioconférence), facultatif.', max_length=300),
        ),
    ]
