# Generated by Django 5.2.17 on 2026-09-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_event_all_day_event_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='creation_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
