# Generated by Django 5.2.17 on 2026-09-09 07:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('governance', '0002_mandate'),
        ('members', '0003_membershipapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuesRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('TO_REGULARIZE', 'À régulariser'), ('PAID', 'Réglée')], default='TO_REGULARIZE', max_length=15)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text="Montant en TND, laissé vide tant qu'il n'est pas connu", max_digits=8, null=True)),
                ('currency', models.CharField(default='TND', max_length=3)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lions_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dues_records', to='governance.lionsyear')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dues_records', to='members.memberprofile')),
            ],
            options={
                'ordering': ['-lions_year__starts_on'],
            },
        ),
        migrations.CreateModel(
            name='DuesChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=15)),
                ('new_status', models.CharField(max_length=15)),
                ('old_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('new_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('motif', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dues_changes_made', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='dues.duesrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='duesrecord',
            constraint=models.UniqueConstraint(fields=('profile', 'lions_year'), name='dues_unique_profile_year'),
        ),
        migrations.AddConstraint(
            model_name='duesrecord',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['TO_REGULARIZE', 'PAID'])), name='dues_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='duesrecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gte', 0), _connector='OR'), name='dues_amount_non_negative'),
        ),
    ]
