# Generated by Django 5.2.1 on 2026-08-20 10:34

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/besbes/Documents/lionsmed/private_media')), upload_to='documents/'),
        ),
    ]
