# Generated by Django 5.2.1 on 2026-08-20 11:49

import core.validators
import django.core.files.storage
import django.core.validators
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/besbes/Documents/lionsmed/private_media')), upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'], message='Format de document non accepté. Extensions autorisées : %(allowed_extensions)s.'), core.validators.MaxFileSizeValidator(15728640)]),
        ),
    ]
